# Generated by Django 5.2 on 2025-06-16 02:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
         migrations.AlterField(
        model_name='profile',
        name='bio',
        field=models.CharField(max_length=550, null=True, blank=True),
        ),
    ]
