# Generated by Django 5.2 on 2025-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
