# Generated by Django 5.2 on 2025-05-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_interaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='state',
            field=models.IntegerField(default=3),
        ),
    ]
